### ISSUE TITLE
Error in running PARIS

### ISSUE THREAD

**Issue by mavershang** [sbenfatto/PARIS#1]
Hi there, glad to open the first issue thread.

I encounter the following error using this script. Could you look into it?

```
library(PARIS)
geneList <- c('ABCB4', 'SORL1')
run_PARIS(imp.score = "raw", 
          omic = c('mutation', 'expression'),
          outdir = "X:\\projects\\p025_SyntheticLethalityInCancerCells\\PARIS_wd\\run1\1",
          genelist_dep = geneList, 
          genelist_feat = NULL)

```

Error
```
Error: Can't subset columns that don't exist.
x Location 2 doesn't exist.
i There are only 1 column.
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning message:
In dir.create(outdir, showWarnings = T) :
  cannot create dir 'X:\projects\p025_SyntheticLethalityInCancerCells\PARIS_wd\run1', reason 'Invalid argument'


```

**Comment by mavershang** [comment]
I figure it out by remove geneList_feat arg. But now have another question: the generated rds is not readable. It pops "unknown file format"

**Comment by sbenfatto** [comment]
Hi, thanks for your feedback and interest in PARIS. Yes, the genelist_feat can't be NULL. Can you load the rds in this way?
`res <- get(load("model.NAME.rds"))`

**Comment by mavershang** [comment]
@sbenfatto thank a lot for the prompt reply. Yes, that works.
Another question: is there a specific order or combination of imp.score required? For example, I failed when using 
imp.score=c('Gini", "Ginicorrected")

**Comment by sbenfatto** [comment]
@mavershang PARIS runs with one of the importance score methods at a time. If you want to use different importance score methods run it multiple times changing the imp.score arg. Same for the omics data to use (mutation/expression).

**Comment by mavershang** [comment]
@sbenfatto I am bit confused. I can understand that if I set imp.score=c("raw", "Gini", "Ginicorrected"), it will run three times using each method and give candidate gene pairs.

But for "omic" option, do you mean it can only consider mutation **OR** expression in a single run? Could it calculate importance score combining both mutation and expression?

```
run_PARIS(
  imp.score = c("raw", "Gini", "Ginicorrected"),
  omic = c("mutation", "expression"),
  outdir = wd,
  genelist_dep
)
```

**Comment by sbenfatto** [comment]
> @sbenfatto I am bit confused. I can understand that if I set imp.score=c("raw", "Gini", "Ginicorrected"), it will run three times using each method and give candidate gene pairs.
> 
> But for "omic" option, do you mean it can only consider mutation **OR** expression in a single run? Could it calculate importance score combining both mutation and expression?
> 
> ```
> run_PARIS(
>   imp.score = c("raw", "Gini", "Ginicorrected"),
>   omic = c("mutation", "expression"),
>   outdir = wd,
>   genelist_dep
> )
> ```

@mavershang both imp.score and omic arguments take only one arg, i.e. the options are in OR. Since mutation and expression features are mathematically different at the moment they can be selected only independently. So, if you want to compare mutation and expression selected features you need to run PARIS 2 times.

For instance:
`run_PARIS(imp.score = "raw", omic = "expression", outdir = "/PARIS_test", genelist_dep = yourgenelist, genelist_feat = yourgenelist2)`
`run_PARIS(imp.score = "raw", omic = "mutation", outdir = "/PARIS_test", genelist_dep = yourgenelist, genelist_feat = yourgenelist2)`
will generate candidate gene pairs using independently mutation and expression features employing the raw importance score.

**Comment by mavershang** [comment]
@sbenfatto Thanks a lot for the explanation.
Is there anyway I can change the default parameter, such as p-value cutoff. and besides the original paper, is there a document or tutorial available?

**Comment by shangl02** [comment]
@sbenfatto, thanks for the help. I have two more question regarding the output
1. what is the scale of importance score, does lower imp score indicate higher correlation?
2. what does the "group" column mean?
Thanks!

**Comment by sbenfatto** [comment]
> @sbenfatto Thanks a lot for the explanation. Is there anyway I can change the default parameter, such as p-value cutoff. and besides the original paper, is there a document or tutorial available?

Not at the moment.

**Comment by sbenfatto** [comment]
> @sbenfatto, thanks for the help. I have two more question regarding the output
> 
>     1. what is the scale of importance score, does lower imp score indicate higher correlation?
> 
>     2. what does the "group" column mean?
>        Thanks!

1. The importance score is scaled between 0 and 1. Where 1 is the highest score obtained within the group.
2. The first letter of the group indicates if the expression or mutation data were used ("e" or "m") and the second letter which importance score method was employed ("r", "g", "c"), raw permutation, Gini or Corrected Gini respectively.

**Comment by shangl02** [comment]
@sbenfatto Thanks!
Regarding the cutoff, should I only consider p-value and coeff, or need to add importance score?

**Comment by sbenfatto** [comment]
> @sbenfatto Thanks! Regarding the cutoff, should I only consider p-value and coeff, or need to add importance score?

p-value and coeff refer to the Pearson correlation coefficient. I'd strongly recommend to use the importance score to rank the results.
